# Copyright (c) 2026 Giancarlo Martinez
# SPDX-License-Identifier: Apache-2.0

#Service Account is the identity for a pod. Equivalent to a suer account
#As users get accounts, programs running in cluster get service accounts answering "who is this"
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appointments-sa