# Copyright (c) 2026 Giancarlo Martinez
# SPDX-License-Identifier: Apache-2.0

# Go and fetch master password generated by RDS with "manage_master_user_password = true" in rds.tf
#TF logs as admin into MySQL RDS DB
data "aws_secretsmanager_secret_version" "db_master" {
  secret_id = module.rds_db.appointments_db_master_user_secret_arn
}

provider "mysql" {
  endpoint = "${module.rds_db.appointments_db_address}:${module.rds_db.appointments_db_port}" #host + port
  username = var.appointments_db_username                                                     #master username
  password = jsondecode(data.aws_secretsmanager_secret_version.db_master.secret_string)["password"]
  tls      = "skip-verify" #encrypt connection
}